-- =========================================================
-- Nexrnn LMS — Migration 13
-- Run AFTER migration_12.sql.
-- Adds profile fields, admin user management, one-time ratings,
-- learner feedback data support, and website visit analytics.
-- =========================================================

-- Profile fields collected during account creation.
alter table profiles add column if not exists gender text;
alter table profiles add column if not exists city text;

alter table profiles drop constraint if exists profiles_gender_check;
alter table profiles
  add constraint profiles_gender_check
  check (gender is null or gender in ('male', 'female', 'other', 'prefer_not_to_say'));

-- Keep signup metadata in the profile row for new accounts.
create or replace function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (
    id, user_registration_id, email, first_name, last_name, phone, gender, city
  )
  values (
    new.id,
    'USR-' || upper(substr(encode(digest(new.id::text, 'sha256'), 'hex'), 1, 12)),
    new.email,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'gender',
    new.raw_user_meta_data->>'city'
  )
  on conflict (id) do update set
    email = excluded.email,
    first_name = coalesce(profiles.first_name, excluded.first_name),
    last_name = coalesce(profiles.last_name, excluded.last_name),
    phone = coalesce(profiles.phone, excluded.phone),
    gender = coalesce(profiles.gender, excluded.gender),
    city = coalesce(profiles.city, excluded.city),
    user_registration_id = coalesce(profiles.user_registration_id, excluded.user_registration_id);
  return new;
end;
$$ language plpgsql security definer set search_path = public;

-- Admins may manage profile fields, but the existing immutable User ID
-- trigger still rejects any attempted User ID change.
drop policy if exists "Admins can update profiles" on profiles;
create policy "Admins can update profiles"
  on profiles for update using (is_admin()) with check (is_admin());

-- Used by the Admin panel to remove a user account and its related LMS rows.
-- This deliberately blocks an admin from deleting their own account.
create or replace function admin_delete_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not is_admin() then
    raise exception 'Only admins can delete users.';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'You cannot delete your own admin account.';
  end if;
  delete from auth.users where id = p_user_id;
  if not found then
    raise exception 'User account not found.';
  end if;
end;
$$;

grant execute on function admin_delete_user(uuid) to authenticated;

-- A course rating is allowed only after every lesson is complete.
create or replace function has_completed_course(p_user_id uuid, p_course_id text)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select count(*) > 0
    and count(*) = count(*) filter (where lp.done = true)
  from lessons l
  join modules m on m.id = l.module_id
  left join lesson_progress lp on lp.lesson_id = l.id and lp.user_id = p_user_id
  where m.course_id = p_course_id
    and exists (
      select 1 from enrollments e
      where e.user_id = p_user_id and e.course_id = p_course_id
    );
$$;

drop policy if exists "Users can update their own rating" on course_ratings;
drop policy if exists "Users can rate courses they're enrolled in" on course_ratings;
create policy "Users can rate completed courses once"
  on course_ratings for insert
  with check (auth.uid() = user_id and has_completed_course(auth.uid(), course_id));

-- Keep the one-rating-per-user-per-course rule even if an older project
-- did not have the unique constraint from schema.sql.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'course_ratings_user_id_course_id_key'
      and conrelid = 'public.course_ratings'::regclass
  ) then
    alter table course_ratings add constraint course_ratings_user_id_course_id_key unique (user_id, course_id);
  end if;
end $$;

-- Website page-view records. The public insert policy allows anonymous
-- visitors, while only admins can read the records in the dashboard.
create table if not exists site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  session_id text not null,
  path text not null,
  user_id uuid references auth.users(id) on delete set null,
  visited_at timestamptz not null default now()
);

alter table site_visits enable row level security;
drop policy if exists "Visitors can record page visits" on site_visits;
create policy "Visitors can record page visits"
  on site_visits for insert
  with check (user_id is null or user_id = auth.uid());
drop policy if exists "Admins can view site visits" on site_visits;
create policy "Admins can view site visits"
  on site_visits for select using (is_admin());
create index if not exists site_visits_visited_at_idx on site_visits (visited_at desc);
create index if not exists site_visits_visitor_id_idx on site_visits (visitor_id);
